# Generated by Django 2.2.4 on 2021-02-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='Authors', to='book_app.Book'),
        ),
    ]
